name: bloc_firebase
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  firebase_core: ^2.13.0 #duno ar reik
  cupertino_icons: ^1.0.2
  firebase_storage: ^11.2.1
  firebase_database: ^10.2.1
  font_awesome_flutter: ^10.4.0
  get_it: ^7.6.0
  firebase_auth: ^4.6.1
  flutter_facebook_auth: ^4.1.2
  google_sign_in: ^5.2.4
  provider: ^6.0.2
  flutter_native_splash: ^2.3.0
  google_fonts: ^4.0.4
  equatable: ^2.0.5
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
    - assets/images/splash_images/
    - assets/images/on_boarding_images/
    - assets/images/welcome_images/
    - assets/fonts/
    - assets/logos/
    - assets/videos/
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_native_splash:
  background_image: assets/images/splash_images/flutter-native-splash-background-image.png
  image: assets/images/splash_images/flutter-native-splash-image.png

  android_12:
    image: assets/images/splash_images/flutter-native-splash-image.png
    background_image: assets/images/splash_images/flutter-native-splash-background-image.png